import { useState } from 'react';
import { Check, Plus, RotateCcw, X } from 'lucide-react';

interface TestCase {
  id: string;
  input: string[];
  output: string;
  status?: 'passed' | 'failed' | 'pending';
  actualOutput?: string;
}

interface TestResult {
  testCaseId: string;
  passed: boolean;
  actualOutput: string;
  expectedOutput: string;
  executionTime?: number;
}

interface TestCaseDisplayProps {
  testCases: TestCase[];
  testResults?: TestResult[];
  onRunTests?: () => void;
  onAddTestCase?: () => void;
  onResetTestCases?: () => void;
  problemParams?: { name: string; label: string }[];
}

const TestCaseDisplay = ({
  testCases,
  testResults = [],
  onRunTests,
  onAddTestCase,
  onResetTestCases,
  problemParams
}: TestCaseDisplayProps) => {
  const [selectedTestCase, setSelectedTestCase] = useState(testCases[0]?.id || '1');
  const [editableInputs, setEditableInputs] = useState<Record<string, string[]>>({});

  // Get current test case
  const currentTestCase = testCases.find(tc => tc.id === selectedTestCase) || testCases[0];
  const currentResult = testResults.find(tr => tr.testCaseId === selectedTestCase);
  
  // Auto-generate parameter labels based on test case inputs
  const autoGeneratedParams = currentTestCase?.input?.map((_, index) => {
    if (index === 0) return { name: 'nums', label: 'Nums' };
    if (index === 1) return { name: 'target', label: 'Target' };
    return { name: `param${index + 1}`, label: `Param ${index + 1}` };
  }) || [];
  
  const displayParams = problemParams || autoGeneratedParams;
  
  // Determine overall status
  const allPassed = testResults.length > 0 && testResults.every(tr => tr.passed);
  const anyFailed = testResults.some(tr => !tr.passed);
  const hasResults = testResults.length > 0;

  // Get test case status
  const getTestCaseStatus = (testCaseId: string): 'passed' | 'failed' | 'pending' => {
    const result = testResults.find(tr => tr.testCaseId === testCaseId);
    if (!result) return 'pending';
    return result.passed ? 'passed' : 'failed';
  };

  // Handle input change for test cases
  const handleInputChange = (paramIndex: number, value: string) => {
    const testCaseId = currentTestCase?.id;
    if (!testCaseId) return;

    setEditableInputs(prev => {
      const currentInputs = prev[testCaseId] || [...(currentTestCase?.input || [])];
      const newInputs = [...currentInputs];
      newInputs[paramIndex] = value;
      return { ...prev, [testCaseId]: newInputs };
    });
  };

  // Get display value for input
  const getInputValue = (paramIndex: number): string => {
    const testCaseId = currentTestCase?.id;
    if (!testCaseId) return '';
    
    // First check if user has edited this input
    if (editableInputs[testCaseId] && editableInputs[testCaseId][paramIndex] !== undefined) {
      return editableInputs[testCaseId][paramIndex];
    }
    
    // Otherwise return the original value from test case
    const originalValue = currentTestCase?.input?.[paramIndex];
    return originalValue !== undefined ? originalValue : '';
  };

  return (
    <div className="flex flex-col gap-4 p-4 bg-[#0a0a0a] border-t border-[#1f1f1f] h-full overflow-y-auto">
      {/* Header with test case tabs and controls */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {/* Test case tabs */}
          {testCases.slice(0, 2).map((testCase, index) => {
            const status = getTestCaseStatus(testCase.id);
            const isActive = selectedTestCase === testCase.id;
            
            return (
              <div key={testCase.id} className="relative inline-flex items-center group">
                <button
                  type="button"
                  onClick={() => setSelectedTestCase(testCase.id)}
                  className={`
                    px-3 h-7 flex items-center gap-1.5 rounded-md
                    transition-all duration-200 text-sm font-medium
                    border backdrop-blur-sm
                    ${isActive 
                      ? status === 'passed' 
                        ? 'bg-green-500/10 border-green-500/30 text-green-400 shadow-[0_0_15px_rgba(34,197,94,0.15)]' 
                        : status === 'failed'
                        ? 'bg-red-500/10 border-red-500/30 text-red-400 shadow-[0_0_15px_rgba(239,68,68,0.15)]'
                        : 'bg-orange-500/10 border-orange-500/30 text-orange-400 shadow-[0_0_15px_rgba(249,115,22,0.15)]'
                      : 'bg-[#141414]/50 border-[#2a2a2a] text-gray-400 hover:bg-[#1a1a1a] hover:border-[#3a3a3a]'
                    }
                  `}
                >
                  {status === 'passed' && (
                    <Check className="w-3.5 h-3.5 text-green-500" />
                  )}
                  {status === 'failed' && (
                    <X className="w-3.5 h-3.5 text-red-500" />
                  )}
                  <span>Case {index + 1}</span>
                </button>
              </div>
            );
          })}

          {/* Add test case button */}
          {onAddTestCase && (
            <button
              type="button"
              onClick={onAddTestCase}
              className="px-3 h-7 flex items-center gap-1 rounded-md text-sm font-medium
                       bg-[#141414]/50 border border-[#2a2a2a] text-gray-400
                       hover:bg-[#1a1a1a] hover:border-[#3a3a3a] hover:text-gray-300
                       transition-all duration-200"
            >
              <Plus className="w-3.5 h-3.5" />
            </button>
          )}
        </div>

        {/* Reset button */}
        {onResetTestCases && (
          <button
            type="button"
            onClick={onResetTestCases}
            className="flex items-center gap-1.5 px-3 h-7 rounded-md text-sm
                     text-gray-400 hover:text-gray-200
                     hover:bg-[#1a1a1a] transition-all duration-200"
          >
            <RotateCcw className="w-3 h-3" />
            <span>Reset</span>
          </button>
        )}
      </div>

      {/* Status indicator */}
      {hasResults && (
        <div className="flex items-center gap-2">
          {allPassed ? (
            <>
              <Check className="w-4 h-4 text-green-500" />
              <span className="font-medium text-green-500 text-sm">Accepted</span>
            </>
          ) : anyFailed ? (
            <>
              <X className="w-4 h-4 text-red-500" />
              <span className="font-medium text-red-500 text-sm">Wrong Answer</span>
            </>
          ) : null}
        </div>
      )}

      {/* Input parameters */}
      {currentTestCase && (
        <div className="flex flex-col gap-3">
          {displayParams.slice(0, currentTestCase.input?.length || 0).map((param, index) => (
            <div key={param.name} className="flex flex-col gap-1">
              <fieldset className="relative rounded-md border border-[#2a2a2a] px-1 bg-[#0f0f0f]/50">
                <legend className="px-2 text-xs font-medium uppercase tracking-wide text-gray-400">
                  {param.label}
                </legend>
                <input
                  type="text"
                  id={`tc-${selectedTestCase}-${param.name}`}
                  value={getInputValue(index)}
                  onChange={(e) => handleInputChange(index, e.target.value)}
                  className="w-full px-2 py-1.5 text-sm bg-transparent border-0 
                           text-gray-200 focus:outline-none focus:ring-0
                           placeholder:text-gray-500"
                  placeholder={`Enter ${param.label.toLowerCase()}...`}
                />
              </fieldset>
            </div>
          ))}
        </div>
      )}

      {/* Output comparison */}
      {hasResults && currentResult && (
        <div className="flex flex-row gap-4">
          {/* Your Output */}
          <fieldset className="relative rounded-md border border-[#2a2a2a] px-3 pb-2 pt-1 flex-1 bg-[#0f0f0f]/50">
            <legend className="px-2 text-xs font-medium uppercase tracking-wide text-gray-400">
              Your Output
            </legend>
            <div className="px-2 py-1">
              <pre className={`text-sm font-mono whitespace-pre-wrap break-words ${
                currentResult.passed ? 'text-green-400' : 'text-red-400'
              }`}>
                {currentResult.actualOutput || 'No output'}
              </pre>
            </div>
          </fieldset>

          {/* Expected Output */}
          <fieldset className="relative rounded-md border border-[#2a2a2a] px-3 pb-2 pt-1 flex-1 bg-[#0f0f0f]/50">
            <legend className="px-2 text-xs font-medium uppercase tracking-wide text-gray-400">
              Expected Output
            </legend>
            <div className="px-2 py-1">
              <pre className="text-sm font-mono whitespace-pre-wrap break-words text-gray-200">
                {currentResult.expectedOutput || currentTestCase?.output || 'No expected output'}
              </pre>
            </div>
          </fieldset>
        </div>
      )}

      {/* Show expected output when no results yet */}
      {!hasResults && currentTestCase && (
        <div className="flex flex-col gap-1">
          <fieldset className="relative rounded-md border border-[#2a2a2a] px-3 pb-2 pt-1 bg-[#0f0f0f]/50">
            <legend className="px-2 text-xs font-medium uppercase tracking-wide text-gray-400">
              Expected Output
            </legend>
            <div className="px-2 py-1">
              <pre className="text-sm font-mono whitespace-pre-wrap break-words text-gray-200">
                {currentTestCase.output}
              </pre>
            </div>
          </fieldset>
        </div>
      )}
    </div>
  );
};

export default TestCaseDisplay;
